# Generated by Django 6.0.5 on 2026-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Фото')),
                ('post_type', models.CharField(choices=[('news', 'Новость'), ('promo', 'Акция')], default='news', max_length=10, verbose_name='Тип')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Новости и акции',
                'ordering': ['-created_at'],
            },
        ),
    ]
