# Generated by Django 6.0.5 on 2026-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=255, verbose_name='Теги')),
                ('pd_consent', models.BooleanField(default=False, verbose_name='Согласие на обработку ПД')),
                ('pd_consent_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на ПД')),
                ('photo_consent', models.BooleanField(default=False, verbose_name='Общее согласие на фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
            },
        ),
    ]
