# Generated by Django 6.0.5 on 2026-05-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo_consent',
        ),
    ]
