# Generated by Django 6.0.5 on 2026-05-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_photo_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pd_consent',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pd_consent_datetime',
        ),
    ]
