# Generated by Django 6.0.5 on 2026-05-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='work_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Формат: {"mon": ["09:00","20:00"], "tue": ["09:00","20:00"]}', verbose_name='Рабочее расписание'),
        ),
        migrations.CreateModel(
            name='SpecialistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='specialist_docs/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Документ специалиста',
                'verbose_name_plural': 'Документы специалиста',
            },
        ),
    ]
