# Generated by Django 6.0.5 on 2026-06-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('specialists', '0002_specialist_work_schedule_specialistdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='specialists', to='services.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='work_schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='Рабочее расписание'),
        ),
    ]
