# Generated by Django 6.0.5 on 2026-06-12 22:12

import django.db.models.deletion
import specialists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_specialist_services_alter_specialist_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Выходной день')),
                ('time_start', models.CharField(blank=True, help_text='ЧЧ:ММ, например 10:00', max_length=5, validators=[specialists.models.validate_time_str], verbose_name='Начало работы')),
                ('time_end', models.CharField(blank=True, help_text='ЧЧ:ММ, например 16:00', max_length=5, validators=[specialists.models.validate_time_str], verbose_name='Конец работы')),
                ('comment', models.CharField(blank=True, help_text='Например: больничный, корпоратив, отпуск', max_length=255, verbose_name='Комментарий')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Исключение в расписании',
                'verbose_name_plural': 'Исключения в расписании',
                'ordering': ['date'],
                'unique_together': {('specialist', 'date')},
            },
        ),
    ]
