# Generated by Django 6.0.5 on 2026-06-13 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_specialistscheduleexception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='work_schedule',
        ),
        migrations.RemoveField(
            model_name='specialistscheduleexception',
            name='is_day_off',
        ),
        migrations.AddField(
            model_name='specialist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='specialistscheduleexception',
            name='time_end',
            field=models.TimeField(blank=True, help_text='Оставьте пустым для выходного дня', null=True, verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='specialistscheduleexception',
            name='time_start',
            field=models.TimeField(blank=True, help_text='Оставьте пустым для выходного дня', null=True, verbose_name='Начало работы'),
        ),
        migrations.CreateModel(
            name='SpecialistWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Начало смены')),
                ('time_end', models.TimeField(verbose_name='Конец смены')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Базовое расписание',
                'ordering': ['weekday'],
                'unique_together': {('specialist', 'weekday')},
            },
        ),
    ]
