# Generated by Django 6.0.5 on 2026-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_remove_specialist_work_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt для главного изображения'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='h1',
            field=models.CharField(blank=True, help_text='Если не заполнен — используется название.', max_length=255, verbose_name='Заголовок страницы (H1)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если не заполнен — используется название.', max_length=255, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически. Можно изменить вручную.', max_length=200, unique=True, verbose_name='URL (slug)'),
        ),
        migrations.AlterField(
            model_name='specialistscheduleexception',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
    ]
