# Generated by Django 6.0.5 on 2026-05-30 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_client_photo_consent'),
        ('services', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(blank=True, verbose_name='Конец')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('no_show', 'Не явился'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='references/', verbose_name='Референс клиента')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('pd_consent_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на обработку ПД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Услуга')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['date', 'time_start'],
            },
        ),
    ]
