# Generated by Django 6.0.5 on 2026-06-13 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_reference_photo_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reference_photo',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reference_photo_2',
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменена'),
        ),
        migrations.CreateModel(
            name='AppointmentReferencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='references/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_photos', to='appointments.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Референс',
                'verbose_name_plural': 'Референсы клиента',
            },
        ),
    ]
