# Generated by Django 6.0.5 on 2026-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(default='Мой салон', max_length=255, verbose_name='Название салона')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Фавиконка')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('color_primary', models.CharField(default='#4F81BD', max_length=7, verbose_name='Основной цвет')),
                ('color_secondary', models.CharField(default='#2E4057', max_length=7, verbose_name='Вторичный цвет')),
                ('color_accent', models.CharField(default='#F6AE2D', max_length=7, verbose_name='Акцентный цвет')),
                ('color_background', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Фон')),
                ('font', models.CharField(default='Roboto', max_length=100, verbose_name='Шрифт')),
                ('privacy_policy', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Политика конфиденциальности (PDF)')),
                ('watermark_type', models.CharField(choices=[('logo', 'Логотип'), ('text', 'Текст')], default='text', max_length=10, verbose_name='Тип водяного знака')),
                ('watermark_text', models.CharField(blank=True, max_length=100, verbose_name='Текст водяного знака')),
                ('watermark_opacity', models.FloatField(default=0.3, verbose_name='Прозрачность водяного знака')),
                ('sections_config', models.JSONField(blank=True, default=list, verbose_name='Конфигурация секций')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
