# Generated by Django 6.0.5 on 2026-06-16 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Главный офис, Филиал на Ленина', max_length=255, verbose_name='Название')),
                ('address', models.TextField(blank=True, help_text='Текстовый адрес для отображения', verbose_name='Адрес')),
                ('map_url', models.TextField(blank=True, help_text='Значение атрибута src из iframe Яндекс Карты', verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('max', 'Мессенджер MAX')], max_length=20, verbose_name='Тип')),
                ('label', models.CharField(help_text='Например: «Администратор», «WhatsApp для записи»', max_length=100, verbose_name='Название')),
                ('value', models.CharField(help_text='Телефон, email, ссылка или @username', max_length=255, verbose_name='Значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('type', models.CharField(choices=[('banner', 'Баннер'), ('services', 'Услуги'), ('team', 'О команде'), ('portfolio', 'Портфолио'), ('news', 'Новости и акции'), ('products', 'Товары'), ('text_image', 'Текст + Изображение'), ('steps', 'Шаги'), ('contacts', 'Контакты и адреса'), ('map', 'Карта')], max_length=20, verbose_name='Тип секции')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('image', models.ImageField(blank=True, help_text='Используется в секциях «Баннер» и «Текст + Изображение»', null=True, upload_to='sections/', verbose_name='Изображение')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видна на сайте')),
                ('anchor', models.SlugField(blank=True, help_text='Например: services, team, booking. Используется в навигации.', max_length=100, verbose_name='Якорь (anchor)')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('page_type', models.CharField(choices=[('services', 'Услуги'), ('team', 'Команда'), ('portfolio', 'Портфолио'), ('news', 'Новости и акции'), ('products', 'Товары')], max_length=20, unique=True, verbose_name='Тип страницы')),
                ('nav_label', models.CharField(max_length=100, verbose_name='Название в навигации')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видна в навигации')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Страница сайта',
                'verbose_name_plural': 'Страницы сайта',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(default='Мой салон', max_length=255, verbose_name='Название салона')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Фавиконка')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('color_primary', models.CharField(default='#4F81BD', max_length=7, verbose_name='Основной цвет')),
                ('color_secondary', models.CharField(default='#2E4057', max_length=7, verbose_name='Вторичный цвет')),
                ('color_accent', models.CharField(default='#F6AE2D', max_length=7, verbose_name='Акцентный цвет')),
                ('color_background', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Фон')),
                ('font', models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Montserrat', 'Montserrat'), ('Lato', 'Lato'), ('Raleway', 'Raleway'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Merriweather', 'Merriweather'), ('PT Sans', 'PT Sans'), ('Ubuntu', 'Ubuntu')], default='Roboto', max_length=100, verbose_name='Шрифт')),
                ('privacy_policy', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Политика конфиденциальности (PDF)')),
                ('watermark_type', models.CharField(choices=[('logo', 'Логотип'), ('text', 'Текст')], default='text', max_length=10, verbose_name='Тип водяного знака')),
                ('watermark_text', models.CharField(blank=True, max_length=100, verbose_name='Текст водяного знака')),
                ('watermark_opacity', models.FloatField(default=0.3, verbose_name='Прозрачность (0.1 — 1.0)')),
                ('captcha_client_key', models.CharField(blank=True, help_text='Клиентский ключ из Яндекс Cloud (sitekey)', max_length=100, verbose_name='SmartCaptcha — клиентский ключ')),
                ('captcha_server_key', models.CharField(blank=True, help_text='Серверный ключ для проверки токена на сервере', max_length=100, verbose_name='SmartCaptcha — серверный ключ')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок (title)')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta description')),
                ('robots', models.CharField(default='index, follow', help_text='Например: index, follow или noindex, nofollow', max_length=50, verbose_name='Robots')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: 01, 1, A, ★', max_length=10, verbose_name='Номер/символ')),
                ('text', models.TextField(verbose_name='Текст шага')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='site_constructor.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='site_constructor.sitesettings', verbose_name='Сайт'),
        ),
    ]
