# Generated by Django 6.0.5 on 2026-05-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_cta_text',
            field=models.CharField(blank=True, default='Записаться', max_length=100, verbose_name='Баннер: текст кнопки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Баннер: фоновое фото'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Баннер: подзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Баннер: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='steps_config',
            field=models.JSONField(blank=True, default=list, help_text='Пример: [{"title": "Запись", "text": "Выберите услугу онлайн"}]', verbose_name='Шаги: список'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='steps_title',
            field=models.CharField(blank=True, default='Как это работает', max_length=255, verbose_name='Шаги: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='table_config',
            field=models.JSONField(blank=True, default=dict, help_text='Пример: {"headers": ["Услуга","Цена"], "rows": [["Маникюр","2500"]]}', verbose_name='Таблица: данные'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='table_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Таблица: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_image_body',
            field=models.TextField(blank=True, verbose_name='Блок текст+фото: текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_image_photo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Блок текст+фото: фото'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_image_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Блок текст+фото: заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font',
            field=models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Montserrat', 'Montserrat'), ('Lato', 'Lato'), ('Raleway', 'Raleway'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Merriweather', 'Merriweather'), ('PT Sans', 'PT Sans'), ('Ubuntu', 'Ubuntu')], default='Roboto', max_length=100, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sections_config',
            field=models.JSONField(blank=True, default=list, help_text='Порядок и видимость секций главной страницы', verbose_name='Конфигурация секций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='watermark_opacity',
            field=models.FloatField(default=0.3, verbose_name='Прозрачность (0.1 — 1.0)'),
        ),
    ]
