# Generated by Django 6.0.5 on 2026-05-31 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0002_sitesettings_banner_cta_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner_cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sections_config',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='steps_config',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='steps_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='table_config',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='table_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='text_image_body',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='text_image_photo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='text_image_title',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('banner', 'Баннер'), ('services', 'Услуги'), ('team', 'О команде'), ('portfolio', 'Портфолио'), ('news', 'Новости и акции'), ('products', 'Товары'), ('text_image', 'Текст + Изображение'), ('steps', 'Шаги'), ('table', 'Таблица'), ('booking', 'Контакты и запись')], max_length=20, verbose_name='Тип секции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='site_constructor.sitesettings', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['order'],
            },
        ),
    ]
