# Generated by Django 6.0.5 on 2026-05-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0003_remove_sitesettings_banner_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_news',
            field=models.BooleanField(default=False, verbose_name='Показывать страницу Новости'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_portfolio',
            field=models.BooleanField(default=True, verbose_name='Показывать страницу Портфолио'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_products',
            field=models.BooleanField(default=False, verbose_name='Показывать страницу Товары'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_services',
            field=models.BooleanField(default=True, verbose_name='Показывать страницу Услуги'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_team',
            field=models.BooleanField(default=True, verbose_name='Показывать страницу Команда'),
        ),
    ]
