# Generated by Django 6.0.5 on 2026-06-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0005_alter_section_options_alter_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, help_text='Используется в секциях «Баннер» и «Текст + Изображение»', null=True, upload_to='sections/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видна на сайте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='watermark_opacity',
            field=models.FloatField(default=0.3, verbose_name='Прозрачность (0.1 — 1.0)'),
        ),
    ]
