# Generated by Django 6.0.5 on 2026-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0006_section_image_section_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='anchor',
            field=models.SlugField(blank=True, help_text='Например: services, team, booking. Используется в навигации.', max_length=100, verbose_name='Якорь (anchor)'),
        ),
    ]
