# Generated by Django 6.0.5 on 2026-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0007_section_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description главной'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description — Новости'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title — Новости'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_slug',
            field=models.SlugField(blank=True, default='news', verbose_name='Slug страницы Новости'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description — Портфолио'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title — Портфолио'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_slug',
            field=models.SlugField(blank=True, default='portfolio', verbose_name='Slug страницы Портфолио'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description — Товары'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title — Товары'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_slug',
            field=models.SlugField(blank=True, default='products', verbose_name='Slug страницы Товары'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='robots',
            field=models.CharField(default='index, follow', help_text='Например: index, follow или noindex, nofollow', max_length=50, verbose_name='Robots'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок главной (title)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description — Услуги'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title — Услуги'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_slug',
            field=models.SlugField(blank=True, default='services', verbose_name='Slug страницы Услуги'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description — Команда'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title — Команда'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_slug',
            field=models.SlugField(blank=True, default='team', verbose_name='Slug страницы Команда'),
        ),
    ]
