# Generated by Django 6.0.5 on 2026-06-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0008_sitesettings_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('page_type', models.CharField(choices=[('services', 'Услуги'), ('team', 'Команда'), ('portfolio', 'Портфолио'), ('news', 'Новости и акции'), ('products', 'Товары')], max_length=20, unique=True, verbose_name='Тип страницы')),
                ('nav_label', models.CharField(max_length=100, verbose_name='Название в навигации')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видна в навигации')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Страница сайта',
                'verbose_name_plural': 'Страницы сайта',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='news_meta_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='news_seo_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='news_slug',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='portfolio_meta_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='portfolio_seo_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='portfolio_slug',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='products_meta_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='products_seo_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='products_slug',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='services_meta_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='services_seo_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='services_slug',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_news',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_portfolio',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_products',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_services',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_team',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='team_meta_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='team_seo_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='team_slug',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок (title)'),
        ),
    ]
