# Generated by Django 6.0.5 on 2026-06-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0009_sitepage_remove_sitesettings_news_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('banner', 'Баннер'), ('services', 'Услуги'), ('team', 'О команде'), ('portfolio', 'Портфолио'), ('news', 'Новости и акции'), ('products', 'Товары'), ('text_image', 'Текст + Изображение'), ('steps', 'Шаги'), ('contacts', 'Контакты и форма'), ('map', 'Карта')], max_length=20, verbose_name='Тип секции'),
        ),
        migrations.CreateModel(
            name='SectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: 01, 1, A, ★', max_length=10, verbose_name='Номер/символ')),
                ('text', models.TextField(verbose_name='Текст шага')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='site_constructor.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
                'ordering': ['order'],
            },
        ),
    ]
