# Generated by Django 6.0.5 on 2026-06-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0010_alter_section_type_sectionstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='captcha_client_key',
            field=models.CharField(blank=True, help_text='Клиентский ключ из Яндекс Cloud (sitekey)', max_length=100, verbose_name='SmartCaptcha - клиентский ключ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='captcha_server_key',
            field=models.CharField(blank=True, help_text='Серверный ключ для проверки токена на сервере', max_length=100, verbose_name='SmartCaptcha - серверный ключ'),
        ),
    ]
