# Generated by Django 6.0.5 on 2026-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0011_sitesettings_captcha_client_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('max', 'Мессенджер MAX')], max_length=20, verbose_name='Тип')),
                ('label', models.CharField(help_text='Например: «Администратор», «WhatsApp для записи»', max_length=100, verbose_name='Название')),
                ('value', models.CharField(help_text='Телефон, email, ссылка или @username', max_length=255, verbose_name='Значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты салона',
                'ordering': ['order'],
            },
        ),
    ]
