# Generated by Django 6.0.5 on 2026-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0012_saloncontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Contact',
            options={'ordering': ('order',), 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты салона'},
        ),
        migrations.AlterField(
            model_name='Contact',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
