# Generated by Django 6.0.6 on 2026-06-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0013_alter_saloncontact_options_alter_saloncontact_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Главный офис, Филиал на Ленина', max_length=255, verbose_name='Название')),
                ('address', models.TextField(blank=True, help_text='Текстовый адрес для отображения', verbose_name='Адрес')),
                ('map_url', models.TextField(blank=True, help_text='Значение атрибута src из iframe Яндекс Карты', verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
