# Generated by Django 6.0.5 on 2026-06-15 20:49
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0016_rename_table_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('order',), 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('banner', 'Баннер'), ('services', 'Услуги'), ('team', 'О команде'), ('portfolio', 'Портфолио'), ('news', 'Новости и акции'), ('products', 'Товары'), ('text_image', 'Текст + Изображение'), ('steps', 'Шаги'), ('contacts', 'Контакты и адреса'), ('map', 'Карта')], max_length=20, verbose_name='Тип секции'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='captcha_client_key',
            field=models.CharField(blank=True, help_text='Клиентский ключ из Яндекс Cloud (sitekey)', max_length=100, verbose_name='SmartCaptcha — клиентский ключ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='captcha_server_key',
            field=models.CharField(blank=True, help_text='Серверный ключ для проверки токена на сервере', max_length=100, verbose_name='SmartCaptcha — серверный ключ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='watermark_opacity',
            field=models.FloatField(default=0.3, verbose_name='Прозрачность (0.1 - 1.0)'),
        ),
    ]