# Generated by Django 6.0.5 on 2026-05-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.FileField(upload_to='consents/', verbose_name='Скан согласия')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_consent', to='appointments.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Согласие на фото',
                'verbose_name_plural': 'Согласия на фото',
            },
        ),
        migrations.CreateModel(
            name='PortfolioWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('appointment', 'Из визита'), ('direct', 'Прямая загрузка')], default='appointment', max_length=20, verbose_name='Источник')),
                ('photo_original', models.ImageField(upload_to='portfolio/original/', verbose_name='Оригинал фото')),
                ('photo_watermarked', models.ImageField(blank=True, upload_to='portfolio/watermarked/', verbose_name='Фото с водяным знаком')),
                ('specialist_liability', models.BooleanField(default=False, verbose_name='Специалист принял ответственность')),
                ('liability_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия ответственности')),
                ('work_date', models.DateField(verbose_name='Дата работы')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='Видно на сайте')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment', verbose_name='Визит')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='Категория услуги')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Работа в портфолио',
                'verbose_name_plural': 'Работы в портфолио',
                'ordering': ['-work_date'],
            },
        ),
    ]
