# Generated by Django 6.0.5 on 2026-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliowork_created_at_portfoliowork_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliowork',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt для главного изображения'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='h1',
            field=models.CharField(blank=True, help_text='Если не заполнен — используется название.', max_length=255, verbose_name='Заголовок страницы (H1)'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если не заполнен — используется название.', max_length=255, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически. Можно изменить вручную.', max_length=200, unique=True, verbose_name='URL (slug)'),
        ),
    ]
