# Generated by Django 6.0.5 on 2026-06-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliowork_alt_text_portfoliowork_h1_and_more'),
        ('services', '0002_service_alt_text_service_h1_service_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliowork',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Конкретная услуга которая была выполнена', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Услуга'),
        ),
    ]
