# Generated by Django 6.0.6 on 2026-06-13 11:23

from django.db import migrations, models


def fill_slugs_product(apps, schema_editor):
    TRANSLIT_TABLE = str.maketrans({
        'а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ё':'yo',
        'ж':'zh','з':'z','и':'i','й':'y','к':'k','л':'l','м':'m',
        'н':'n','о':'o','п':'p','р':'r','с':'s','т':'t','у':'u',
        'ф':'f','х':'kh','ц':'ts','ч':'ch','ш':'sh','щ':'sch',
        'ъ':'','ы':'y','ь':'','э':'e','ю':'yu','я':'ya',
        'А':'A','Б':'B','В':'V','Г':'G','Д':'D','Е':'E','Ё':'Yo',
        'Ж':'Zh','З':'Z','И':'I','Й':'Y','К':'K','Л':'L','М':'M',
        'Н':'N','О':'O','П':'P','Р':'R','С':'S','Т':'T','У':'U',
        'Ф':'F','Х':'Kh','Ц':'Ts','Ч':'Ch','Ш':'Sh','Щ':'Sch',
        'Ъ':'','Ы':'Y','Ь':'','Э':'E','Ю':'Yu','Я':'Ya',
    })
    from django.utils.text import slugify

    def ru_slugify(text):
        return slugify(str(text).translate(TRANSLIT_TABLE))

    Model = apps.get_model('products', 'Product')
    used = set()
    for obj in Model.objects.all():
        base = ru_slugify(getattr(obj, 'name') or str(obj.pk)) or str(obj.pk)
        slug, counter = base, 1
        while slug in used or Model.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
            slug = f'{base}-{counter}'
            counter += 1
        used.add(slug)
        obj.slug = slug
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt для главного изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='h1',
            field=models.CharField(blank=True, help_text='Если не заполнен - используется название.', max_length=255, verbose_name='Заголовок страницы (H1)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если не заполнен - используется название.', max_length=255, verbose_name='SEO заголовок (title)'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE products_product
                    ADD COLUMN IF NOT EXISTS slug varchar(200) NOT NULL DEFAULT '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(fill_slugs_product, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS products_product_slug_70d3148d_like;
                ALTER TABLE products_product
                    DROP CONSTRAINT IF EXISTS products_product_slug_key;
                ALTER TABLE products_product
                    ADD CONSTRAINT products_product_slug_key UNIQUE (slug);
                CREATE INDEX products_product_slug_70d3148d_like
                    ON products_product (slug varchar_pattern_ops);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]